-- MySQL Script generated by MySQL Workbench
-- Sun Aug 24 22:08:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8 ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`ventas` ;

CREATE TABLE IF NOT EXISTS `Optica`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_clientes` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_gafas` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `Optica`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `Optica`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_gafas1`
    FOREIGN KEY (`id_gafas`)
    REFERENCES `Optica`.`gafas` (`id_gafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`clientes` ;

CREATE TABLE IF NOT EXISTS `Optica`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `fecha_registro` DATE NOT NULL,
  `recomendacion` INT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`empleado` ;

CREATE TABLE IF NOT EXISTS `Optica`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `Optica`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`gafas` ;

CREATE TABLE IF NOT EXISTS `Optica`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion` VARCHAR(45) NOT NULL,
  `tipo_montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_cristal` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_gafas`),
  CONSTRAINT `fk_gafas_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Optica`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gafas_proveedor_idx` ON `Optica`.`gafas` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Optica`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`ventas` ;

CREATE TABLE IF NOT EXISTS `Optica`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_clientes` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_gafas` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `Optica`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `Optica`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_gafas1`
    FOREIGN KEY (`id_gafas`)
    REFERENCES `Optica`.`gafas` (`id_gafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_clientes1_idx` ON `Optica`.`ventas` (`id_clientes` ASC) VISIBLE;

CREATE INDEX `fk_ventas_empleado1_idx` ON `Optica`.`ventas` (`id_empleado` ASC) VISIBLE;

CREATE INDEX `fk_ventas_gafas1_idx` ON `Optica`.`ventas` (`id_gafas` ASC) VISIBLE;

USE `Optica` ;

-- -----------------------------------------------------
-- Placeholder table for view `Optica`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `Optica`;
DROP  IF EXISTS `Optica`.`routine1`;

DELIMITER $$
USE `Optica`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `Optica`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`view1`;
DROP VIEW IF EXISTS `Optica`.`view1` ;
USE `Optica`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
