-- MySQL Script generated by MySQL Workbench
-- Tue Aug 26 14:29:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`tienda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pedido` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_recibido` DATETIME NOT NULL,
  `modo_entrega` ENUM('domicilio', 'recogida') NOT NULL,
  `id_producto` INT NOT NULL,
  `precio` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`empleado` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `tipo` ENUM('cocinero', 'repartidor') NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedido_a_domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pedido_a_domicilio` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedido_a_domicilio` (
  `id_pedido_a_domicilio` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_entrega` DATETIME NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido_a_domicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`categoria_pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoria_pizza` (
  `id_categoria_pizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`producto` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) CHARACTER SET 'DEFAULT' NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `tipo` ENUM('pizza', 'hamburguesa', 'bebida') NOT NULL,
  `precio` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_categoria_pizza` INT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`cantidad_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`cantidad_productos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`cantidad_productos` (
  `id_cantidad_productos` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_cantidad_productos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
