-- MySQL Script generated by MySQL Workbench
-- Sat Sep 13 13:46:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`tienda` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pedido` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_recibido` DATETIME NOT NULL,
  `modo_entrega` ENUM('domicilio', 'recogida') NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Pizzeria`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_tienda1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `Pizzeria`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_cliente_idx` ON `Pizzeria`.`pedido` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_pedido_tienda1_idx` ON `Pizzeria`.`pedido` (`id_tienda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`empleado` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `tipo` ENUM('cocinero', 'repartidor') NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  CONSTRAINT `fk_empleado_tienda1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `Pizzeria`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empleado_tienda1_idx` ON `Pizzeria`.`empleado` (`id_tienda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pedido_a_domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pedido_a_domicilio` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pedido_a_domicilio` (
  `id_pedido_a_domicilio` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_entrega` DATETIME NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido_a_domicilio`),
  CONSTRAINT `fk_pedido_a_domicilio_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `Pizzeria`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_a_domicilio_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `Pizzeria`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_a_domicilio_empleado1_idx` ON `Pizzeria`.`pedido_a_domicilio` (`id_empleado` ASC) VISIBLE;

CREATE INDEX `fk_pedido_a_domicilio_pedido1_idx` ON `Pizzeria`.`pedido_a_domicilio` (`id_pedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`categoria_pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoria_pizza` (
  `id_categoria_pizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`producto` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) COLLATE 'DEFAULT' NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `tipo` ENUM('pizza', 'hamburguesa', 'bebida') NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_categoria_pizza` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_producto_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `Pizzeria`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_categoria_pizza1`
    FOREIGN KEY (`id_categoria_pizza`)
    REFERENCES `Pizzeria`.`categoria_pizza` (`id_categoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_producto_pedido1_idx` ON `Pizzeria`.`producto` (`id_pedido` ASC) VISIBLE;

CREATE INDEX `fk_producto_categoria_pizza1_idx` ON `Pizzeria`.`producto` (`id_categoria_pizza` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pizzeria`.`cantidad_de_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`cantidad_de_productos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`cantidad_de_productos` (
  `id_cantidad_de_productos` INT NOT NULL AUTO_INCREMENT,
  `pedido_id_pedido` INT NOT NULL,
  `producto_id_producto` INT NOT NULL,
  `cantidad_de_productoscol` INT NOT NULL,
  PRIMARY KEY (`id_cantidad_de_productos`),
  CONSTRAINT `fk_cantidad_de_productos_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `Pizzeria`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cantidad_de_productos_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `Pizzeria`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cantidad_de_productos_pedido1_idx` ON `Pizzeria`.`cantidad_de_productos` (`pedido_id_pedido` ASC) VISIBLE;

CREATE INDEX `fk_cantidad_de_productos_producto1_idx` ON `Pizzeria`.`cantidad_de_productos` (`producto_id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
